apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-lv7d
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0012-tenant/tkrw-pr712-0075-0012-app/devfile-sample-lv7d@sha256:71afbde9e9b14b4dd360994ff5d4ccdcc0b731d20234589f9809bb73fae06189
        name: my-nodejs
        resources: {}
status: {}
